-- IELTS BandBoost MVP schema
-- Run this in Supabase SQL Editor after creating your project.

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  title text not null,
  skill text not null check (skill in ('Listening','Reading','Writing','Speaking','Vocabulary','Grammar')),
  level text not null check (level in ('Beginner','Intermediate','Advanced')),
  duration text,
  youtube_video_id text,
  teacher text default 'Curated IELTS Lesson',
  notes jsonb default '[]'::jsonb,
  practice_set_id bigint,
  created_at timestamptz default now()
);

create table if not exists public.practice_questions (
  id bigint generated by default as identity primary key,
  practice_set_id bigint not null,
  skill text not null,
  question_type text not null,
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer text not null,
  explanation text,
  created_at timestamptz default now()
);

create table if not exists public.practice_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  skill text not null,
  score int not null,
  total int not null,
  estimated_band numeric(3,1) not null,
  weak_area text,
  created_at timestamptz default now()
);

create table if not exists public.saved_words (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  word text not null,
  meaning text,
  example text,
  created_at timestamptz default now()
);

alter table public.practice_attempts enable row level security;
alter table public.saved_words enable row level security;

create policy "Users can read own attempts"
  on public.practice_attempts for select
  using (auth.uid() = user_id);

create policy "Users can insert own attempts"
  on public.practice_attempts for insert
  with check (auth.uid() = user_id);

create policy "Users can read own saved words"
  on public.saved_words for select
  using (auth.uid() = user_id);

create policy "Users can insert own saved words"
  on public.saved_words for insert
  with check (auth.uid() = user_id);
